site_name: Web Applications Security
site_description: Práctica de Seguridad y Auditoría de Sistemas - ByteVault Web Security Lab
site_url: https://betooxx.github.io/webapps.github.io/

theme:
  name: material
  language: es
  icon:
    logo: material/shield-lock
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight

nav:
  - Inicio: index.md

  - Presentación:
      - presentacion/index.md
      - ¿Qué es una Web App?: presentacion/web-apps.md
      - Seguridad y objetivos de ataque: presentacion/seguridad.md
      - OWASP Top 10:2025: presentacion/owasp.md
      - Herramientas de auditoría: presentacion/herramientas.md
      - Guion de exposición: presentacion/guion.md

  - Manual técnico:
      - manual/index.md
      - 1. Preparar Kali en WSL: manual/entorno.md
      - 2. ByteVault vulnerable: manual/vulnerable.md
      - 3. Reconocimiento: manual/reconocimiento.md
      - 4. SQL Injection: manual/sql-injection.md
      - 5. Stored XSS: manual/xss.md
      - 6. IDOR / Broken Access Control: manual/idor.md
      - 7. OWASP ZAP: manual/zap.md
      - 8. ByteVault segura: manual/segura.md
      - 9. Comparación final: manual/comparacion.md

  - Resultados:
      - resultados/index.md
      - Recomendaciones: resultados/recomendaciones.md
      - Conclusiones: resultados/conclusiones.md
      - Referencias: resultados/referencias.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false
