site_name: VaultStore Web Security Lab
site_description: Práctica de Seguridad en Aplicaciones Web
site_author: Seguridad y Auditoría de Sistemas

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - scheme: slate
      primary: blue
      accent: light blue

nav:
  - Inicio: index.md
  - Preparación del laboratorio: preparacion.md
  - Reconocimiento:
      - WhatWeb, Nikto y Nmap: reconocimiento.md
  - Pruebas de seguridad:
      - SQL Injection, XSS e IDOR: pruebas-manuales.md
      - OWASP ZAP: zap.md
  - Aplicación segura: aplicacion-segura.md
  - Resultados y conclusiones: resultados.md
  - Glosario: glosario.md

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
