site_name: VaultStore Web Security Lab
site_description: Documentación académica sobre seguridad y auditoría de aplicaciones web
site_author: Seguridad y Auditoría de Sistemas

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - scheme: slate
      primary: blue
      accent: light blue

nav:
  - Inicio: index.md
  - Presentación:
      - Introducción: introduccion.md
      - OWASP Top 10: owasp.md
      - Herramientas de auditoría: herramientas.md
  - Laboratorio:
      - SQL Injection: sql-injection.md
      - Stored XSS: stored-xss.md
      - IDOR: idor.md
      - OWASP ZAP: zap.md
  - Seguridad:
      - Aplicación segura: aplicacion-segura.md
      - Comparación: comparacion.md
      - Conclusiones: conclusiones.md
  - Glosario: glosario.md

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
